block_definitions:
    tags:
        name: 'Content tags'
        view_types:
            tags:
                name: 'Content tags'

    wsc_container:
        name: 'WSC container'
        view_types:
            wsc_container:
                name: 'WSC container'
    text:
        view_types:
            red_text:
                name: 'Red text'

view:
    block_view:
        default:
            tags:
                match:
                    block\definition: tags
                    block\view_type: tags
                template: '@ngbm/block/tags.html.twig'
            wsc_container:
                match:
                    block\definition: wsc_container
                    block\view_type: wsc_container
                template: '@ngbm/block/wsc_container.html.twig'
            text\red:
                match:
                    block\definition: text
                    block\view_type: red_text
                template: '@ngbm/block/text/red_text.html.twig'
        api:
            tags:
                match:
                    block\definition: tags
                template: '@NetgenWebSummerCamp/ngbm/api/block/tags.html.twig'
            wsc_container:
                match:
                    block\definition: wsc_container
                template: '@NetgenWebSummerCamp/ngbm/api/block/wsc_container.html.twig'
