imports:
    - { resource: ../config.yml }
    - { resource: ezplatform.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/dev/routing.yml'
        strict_requirements: true
    profiler:
        only_exceptions: false
        only_master_requests: true
    assets:
        json_manifest_path: '%kernel.project_dir%/web/build_dev/manifest.json'

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type: '%log_type%'
            path: '%log_path%'
            level: debug
            channels: ['!event', '!doctrine']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911

        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
